### ISSUE TITLE
AttributeError: module 'faulthandler' has no attribute 'register' on Windows

### ISSUE THREAD

**Issue by cgohlke** [ipython/ipykernel#107]
Using `ipykernel-4.3.0` on Windows (any Python version) raises `AttributeError: module 'faulthandler' has no attribute 'register'` because [faulthandler.register is not available on Windows](https://docs.python.org/3/library/faulthandler.html#faulthandler.register).
```
[I 16:56:07.962 NotebookApp] Kernel started: 3ada1467-e56a-41de-af2b-237fc7349760
Traceback (most recent call last):
  File "X:\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "X:\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "X:\Python35\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "X:\Python35\lib\site-packages\traitlets\config\application.py", line 588, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "X:\Python35\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "X:\Python35\lib\site-packages\ipykernel\kernelapp.py", line 417, in initialize
    self.init_io()
  File "X:\Python35\lib\site-packages\ipykernel\kernelapp.py", line 316, in init_io
    self.patch_io()
  File "X:\Python35\lib\site-packages\ipykernel\kernelapp.py", line 326, in patch_io
    faulthandler_register = faulthandler.register
AttributeError: module 'faulthandler' has no attribute 'register'
[I 16:56:10.960 NotebookApp] KernelRestarter: restarting kernel (1/5)
```

**Comment by Carreau** [comment]
Darn. indeed. Sorry.

**Comment by minrk** [comment]
Fixed by #108. Will release 4.3.1 with the fix shortly. Sorry, @cgohlke! Thanks for the catch.

**Comment by minrk** [comment]
Just pushed 4.3.1

**Comment by takluyver** [comment]
Thanks Min :+1:

**Comment by cgohlke** [comment]
Thank you!

**Comment by matthew-brett** [comment]
Worth setting up appveyor tests for repo?

**Comment by Carreau** [comment]
Not sure.
