### ISSUE TITLE
"ModuleNotFoundError: No module named 'comm'" when running 'python -m ipykernel install'

### ISSUE THREAD

**Issue by brad-eisenhauer** [ipython/ipykernel#1225]
Python version: 3.10.14
ipykernel version: 6.29.4

Command:
```shell
$ python -m ipykernel install --user --name=my-venv
```

Result:
```shell
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.14/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/beise/[redacted]/.venv/lib/python3.10/site-packages/ipykernel/__main__.py", line 3, in <module>
    from ipykernel import kernelapp as app
  File "/Users/beise/[redacted]/.venv/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 54, in <module>
    from .ipkernel import IPythonKernel
  File "/Users/beise/[redacted]/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 15, in <module>
    import comm
ModuleNotFoundError: No module named 'comm'
```

Expected result:
```shell
Installed kernelspec my-venv in /Users/beise/Library/Application Support/Jupyter/kernels/my-venv
```

Works properly with v 6.29.3.

**Comment by TiansuYu** [comment]
Same issue with `6.16.0`
