### ISSUE TITLE
nosetests ipykernel

### ISSUE THREAD

**Issue by xyniceboy** [ipython/ipykernel#124]
E:\install_work\ipykernel-4.3.1>nosetests ipykernel
.....................E.E...S.....................................................
======================================================================
ERROR: printing from forked mp.Process
----------------------------------------------------------------------
Traceback (most recent call last):
  File "e:\install_work\python2.7\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "e:\install_work\python2.7\lib\site-packages\numpy\testing\decorators.py", line 215, in knownfailer
    raise KnownFailureException(msg)
KnownFailureException: subprocess prints fail on Windows

======================================================================
ERROR: error in mp.Process doesn't crash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "e:\install_work\python2.7\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "e:\install_work\python2.7\lib\site-packages\numpy\testing\decorators.py", line 215, in knownfailer
    raise KnownFailureException(msg)
KnownFailureException: subprocess prints fail on Windows

----------------------------------------------------------------------
Ran 81 tests in 26.038s

FAILED (SKIP=1, errors=2)

E:\install_work\ipykernel-4.3.1>

**Comment by Carreau** [comment]
These are expected KnownFailure, the question is why does it not report it as known fail on your system.
