### ISSUE TITLE
Jupyter fails to load kernel with ipykernel 4.3.1 but works with 4.1.1

### ISSUE THREAD

**Issue by avishapiro** [ipython/ipykernel#139]
I use conda to update packages, often `conda update --all`. My Python 3 conda environments suddenly failed on Windows 7. I traced it to updating ipykernel. I reverted to 4.1.1 and Jupyter loads correctly.  Here was the traceback:

```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py35\lib\site-packages\notebook\base\handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda3\envs\py35\lib\site-packages\notebook\services\sessions\handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda3\envs\py35\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_name)
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Anaconda3\envs\py35\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 1008, in run
    value = future.result()
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "C:\Anaconda3\envs\py35\lib\site-packages\tornado\gen.py", line 282, in wrapper
    yielded = next(result)
  File "C:\Anaconda3\envs\py35\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Anaconda3\envs\py35\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda3\envs\py35\lib\site-packages\jupyter_client\manager.py", line 243, in start_kernel
    **kw)
  File "C:\Anaconda3\envs\py35\lib\site-packages\jupyter_client\manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda3\envs\py35\lib\site-packages\jupyter_client\launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda3\envs\py35\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\envs\py35\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

For reference, `conda info` produces:

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.7
  conda-build version : 1.20.3
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3\envs\py35
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/avishapiro/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/avishapiro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/auto/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/auto/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\avi.shapiro\.condarc
    is foreign system : False
```

**Comment by minrk** [comment]
What do you get from:

    jupyter kernelspec list

?

**Comment by avishapiro** [comment]
@minrk: I get
```
Available kernels:
  python2    C:\ProgramData\jupyter\kernels\python2
  python3    C:\ProgramData\jupyter\kernels\python3
```

I have other environments but the same kernels are listed. I've installed some notebook extensions with partial success too in case that's relevant.

**Comment by minrk** [comment]
Try:

    ipython kernel install

to register a new kernelspec for IPython. It's possible the kernelspec file got stale as envs were moved / deleted.

**Comment by avishapiro** [comment]
I'll note that ipykernel 4.2 also works when 4.3 wouid not. @minrk Thanks for the suggestion. Everything seems to be working now with 4.3 in jupyter. The kernel.json file didn't change though. Does `ipython kernel install` do anything else? Does it matter which environment I run that command in (assuming py35 in all)?

**Comment by minrk** [comment]
No, that's all `ipython kernel install does` is write the kernelspec. Does the output of `jupyter kernelspec list` change? Maybe it put the file somewhere else.

**Comment by SylvainCorlay** [comment]
Closing as outdated.
