### ISSUE TITLE
ZMQIOLoop fails with Tornado 5

### ISSUE THREAD

**Issue by pitrou** [ipython/ipykernel#277]
Tornado 5 (in development) removes configurability of IOLoop on Python 3. In turn, this breaks ipykernel which wants to install the ZMQ IOLoop:
```
Traceback (most recent call last):
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/antoine/distributed/distributed/_ipython_utils.py", line 235, in _start
    app.initialize([])
  File "<decorator-gen-123>", line 2, in initialize
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 444, in initialize
    zmq_ioloop.install()
  File "/home/antoine/miniconda3/envs/dask36/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 215, in install
    ioloop.IOLoop.configure(ZMQIOLoop)
  File "/home/antoine/tornado/tornado/ioloop.py", line 173, in configure
    "only AsyncIOLoop is allowed when asyncio is available")
RuntimeError: only AsyncIOLoop is allowed when asyncio is available
```

cc @bdarnell who might give more guidance here.

**Comment by Carreau** [comment]
Thanks for the heads up.

**Comment by minrk** [comment]
pyzmq 17.0 (in beta now) should work with tornado on asyncio. I'm still trying to chase down some edge cases of missed events before releasing.

**Comment by takluyver** [comment]
I think we've got ipykernel working with tornado 5.0a1 now, if one uses the beta version of pyzmq.
