### ISSUE TITLE
Install broken on 4.9.0 / Python 2

### ISSUE THREAD

**Issue by matthew-brett** [ipython/ipykernel#338]
From Python 2 pip:

```
pip install ipykernel
```

This error:

```
Building wheels for collected packages: ipykernel, tornado, scandir
  Running setup.py bdist_wheel for ipykernel ... error
  Complete output from command /Users/brettmz/.virtualenvs/test/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/bg/k1y95mtx0r583fzgqxk6vxy80000gn/T/pip-install-6Gxg_A/ipykernel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/bg/k1y95mtx0r583fzgqxk6vxy80000gn/T/pip-wheel-4unCPn --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/bg/k1y95mtx0r583fzgqxk6vxy80000gn/T/pip-install-6Gxg_A/ipykernel/setup.py", line 91, in <module>
      from ipykernel.kernelspec import write_kernel_spec, make_ipkernel_cmd, KERNEL_NAME
    File "ipykernel/__init__.py", line 2, in <module>
      from .connect import *
    File "ipykernel/connect.py", line 13, in <module>
      from IPython.core.profiledir import ProfileDir
  ImportError: No module named IPython.core.profiledir
```

The installation somehow seems to succeed nevertheless, though the error code does break a few Travis-CI runs - see:

https://travis-ci.org/matthew-brett/nb2plots/builds/422849736

and

https://travis-ci.org/matthew-brett/nb2plots/jobs/422849744

**Comment by mosrosem** [comment]
I have installed ipykernel in MacOS and couldn't replicate the error, I am using python 2.7.14, installation was successful. You can check on https://github.com/ipython/ipykernel/issues/250, something similar happened :)

**Comment by joshvillbrandt** [comment]
I'm getting this as well. I'm not installing ipykernel directly - seems like one of my dependencies need this.

I first noticed this in my project's CI, and as @matthew-brett mentioned, I am also able to reproduce in my dev machine with a clean virtualenv.

**Comment by galbramc** [comment]
I also get this problem with clean virtualenvs on both OSX and Linux. 
However, if I try installing it again pip says it is already installed!? All with python 2.7.
```
16:21 $ virtualenv venv
16:22 $ . venv/bin/activate
16:23 $ pip install ipykernel

Collecting ipykernel
  Using cached https://files.pythonhosted.org/packages/83/2d/1e9860d470725ef22a2c06c15d082ca06d425e91eba1a1292bb0165af128/ipykernel-4.9.0.tar.gz
Collecting ipython>=4.0.0 (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/b0/88/d996ab8be22cea1eaa18baee3678a11265e18cf09974728d683c51102148/ipython-5.8.0-py2-none-any.whl
Collecting traitlets>=4.1.0 (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting jupyter_client (from ipykernel)
  Using cached https://files.pythonhosted.org/packages/94/dd/fe6c4d683b09eb05342bd2816b7779663f71762b4fa9c2d5203d35d17354/jupyter_client-5.2.3-py2.py3-none-any.whl
Collecting tornado>=4.0 (from ipykernel)
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (40.2.0)
Collecting simplegeneric>0.8 (from ipython>=4.0.0->ipykernel)
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/7d/cd/1750d6c35fe86d35f8562091737907f234b78fdffab42b29c72b1dd861f4/backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting pygments (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting appnope; sys_platform == "darwin" (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/87/a9/7985e6a53402f294c8f0e8eff3151a83f1fb901fa92909bb3ff29b4d22af/appnope-0.1.0-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl
Collecting pickleshare (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/9f/17/daa142fc9be6b76f26f24eeeb9a138940671490b91cb5587393f297c8317/pickleshare-0.7.4-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/d1/b0/1a6c262da35c779dd79550137aa7c298a424987240a28792ec5ccf48f848/prompt_toolkit-1.0.15-py2-none-any.whl
Collecting decorator (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/66/a7/9f8d84f31728d78beade9b1271ccbfb290c41c1e4dc13dbd4997ad594dcd/pathlib2-2.3.2-py2.py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.1.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting six (from traitlets>=4.1.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting enum34; python_version == "2.7" (from traitlets>=4.1.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting jupyter-core (from jupyter_client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl
Collecting pyzmq>=13 (from jupyter_client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/e5/28/63a6d14e8ccd224f1faa9df2144fde5bb130dda086eaabb288b2919dcd10/pyzmq-17.1.2-cp27-cp27m-macosx_10_6_intel.whl
Collecting python-dateutil>=2.1 (from jupyter_client->ipykernel)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=4.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/7d/56/6f3ac1b816d0cd8994e83d0c4e55bc64567532f7dc543378bd87f81cebc7/backports_abc-0.5-py2.py3-none-any.whl
Collecting futures (from tornado>=4.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting singledispatch (from tornado>=4.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython>=4.0.0->ipykernel)
Building wheels for collected packages: ipykernel
  Running setup.py bdist_wheel for ipykernel ... error
  Complete output from command /Users/galbramc/venv/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hd/fnf0vk0j6lg0mdgp5s_dwh6r0000gq/T/pip-install-vC5trQ/ipykernel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/hd/fnf0vk0j6lg0mdgp5s_dwh6r0000gq/T/pip-wheel-64SmPy --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/hd/fnf0vk0j6lg0mdgp5s_dwh6r0000gq/T/pip-install-vC5trQ/ipykernel/setup.py", line 91, in <module>
      from ipykernel.kernelspec import write_kernel_spec, make_ipkernel_cmd, KERNEL_NAME
    File "ipykernel/__init__.py", line 2, in <module>
      from .connect import *
    File "ipykernel/connect.py", line 13, in <module>
      from IPython.core.profiledir import ProfileDir
  ImportError: No module named IPython.core.profiledir
  
  ----------------------------------------
  Failed building wheel for ipykernel
  Running setup.py clean for ipykernel
Failed to build ipykernel
Installing collected packages: ipython-genutils, decorator, six, enum34, traitlets, simplegeneric, backports.shutil-get-terminal-size, pygments, appnope, ptyprocess, pexpect, scandir, pathlib2, pickleshare, wcwidth, prompt-toolkit, ipython, backports-abc, futures, singledispatch, tornado, jupyter-core, pyzmq, python-dateutil, jupyter-client, ipykernel
  Running setup.py install for ipykernel ... done
Successfully installed appnope-0.1.0 backports-abc-0.5 backports.shutil-get-terminal-size-1.0.0 decorator-4.3.0 enum34-1.1.6 futures-3.2.0 ipykernel-4.9.0 ipython-5.8.0 ipython-genutils-0.2.0 jupyter-client-5.2.3 jupyter-core-4.4.0 pathlib2-2.3.2 pexpect-4.6.0 pickleshare-0.7.4 prompt-toolkit-1.0.15 ptyprocess-0.6.0 pygments-2.2.0 python-dateutil-2.7.3 pyzmq-17.1.2 scandir-1.9.0 simplegeneric-0.8.1 singledispatch-3.4.0.3 six-1.11.0 tornado-5.1 traitlets-4.3.2 wcwidth-0.1.7

16:24 $ pip install ipykernel
Requirement already satisfied: ipykernel in ./venv/lib/python2.7/site-packages (4.9.0)
Requirement already satisfied: ipython>=4.0.0 in ./venv/lib/python2.7/site-packages (from ipykernel) (5.8.0)
Requirement already satisfied: traitlets>=4.1.0 in ./venv/lib/python2.7/site-packages (from ipykernel) (4.3.2)
Requirement already satisfied: jupyter_client in ./venv/lib/python2.7/site-packages (from ipykernel) (5.2.3)
Requirement already satisfied: tornado>=4.0 in ./venv/lib/python2.7/site-packages (from ipykernel) (5.1)
Requirement already satisfied: setuptools>=18.5 in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (40.2.0)
Requirement already satisfied: simplegeneric>0.8 in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (0.8.1)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (1.0.0)
Requirement already satisfied: pygments in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (2.2.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (0.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (4.6.0)
Requirement already satisfied: pickleshare in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (0.7.4)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (1.0.15)
Requirement already satisfied: decorator in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (4.3.0)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in ./venv/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel) (2.3.2)
Requirement already satisfied: ipython-genutils in ./venv/lib/python2.7/site-packages (from traitlets>=4.1.0->ipykernel) (0.2.0)
Requirement already satisfied: six in ./venv/lib/python2.7/site-packages (from traitlets>=4.1.0->ipykernel) (1.11.0)
Requirement already satisfied: enum34; python_version == "2.7" in ./venv/lib/python2.7/site-packages (from traitlets>=4.1.0->ipykernel) (1.1.6)
Requirement already satisfied: jupyter-core in ./venv/lib/python2.7/site-packages (from jupyter_client->ipykernel) (4.4.0)
Requirement already satisfied: pyzmq>=13 in ./venv/lib/python2.7/site-packages (from jupyter_client->ipykernel) (17.1.2)
Requirement already satisfied: python-dateutil>=2.1 in ./venv/lib/python2.7/site-packages (from jupyter_client->ipykernel) (2.7.3)
Requirement already satisfied: backports-abc>=0.4 in ./venv/lib/python2.7/site-packages (from tornado>=4.0->ipykernel) (0.5)
Requirement already satisfied: futures in ./venv/lib/python2.7/site-packages (from tornado>=4.0->ipykernel) (3.2.0)
Requirement already satisfied: singledispatch in ./venv/lib/python2.7/site-packages (from tornado>=4.0->ipykernel) (3.4.0.3)
Requirement already satisfied: ptyprocess>=0.5 in ./venv/lib/python2.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel) (0.6.0)
Requirement already satisfied: wcwidth in ./venv/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel) (0.1.7)
Requirement already satisfied: scandir; python_version < "3.5" in ./venv/lib/python2.7/site-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython>=4.0.0->ipykernel) (1.9.0)
```

**Comment by minrk** [comment]
The python2 wheel hadn't been uploaded yet for 4.9. It's up now, so this should work. And #339 should fix install from sdist going forward

**Comment by matthew-brett** [comment]
Thanks - my CI tests are passing now too.
