### ISSUE TITLE
Tests: NameError: name 'dec' is not defined

### ISSUE THREAD

**Issue by hroncok** [ipython/ipykernel#397]
I try to run the tests but both with pytest and nose I get: NameError: name 'dec' is not defined

This is what I did on current master (9d7a743cdd6ab5e7e6b11025b2a68820fe17cc32):

```
$ python3.8 -m venv __venv38__
$ . __venv38__/bin/activate

$ pip install --upgrade setuptools pip
...
Requirement already up-to-date: pip in ./__venv38__/lib/python3.8/site-packages (19.0.3)
Successfully installed setuptools-41.0.0

$ pip install --pre --upgrade --upgrade-strategy=eager .[test]
...
Successfully installed atomicwrites-1.3.0 attrs-19.1.0 backcall-0.1.0 coverage-5.0a4 decorator-4.4.0 ipykernel-5.2.0.dev0 ipython-7.4.0 ipython-genutils-0.2.0 jedi-0.13.3 jupyter-client-5.2.4 jupyter-core-4.4.0 more-itertools-7.0.0 nose-1.3.7 parso-0.4.0 pexpect-4.7.0 pickleshare-0.7.5 pluggy-0.9.0 prompt-toolkit-2.0.9 ptyprocess-0.6.0 py-1.8.0 pygments-2.3.1 pytest-4.4.0 pytest-cov-2.6.1 python-dateutil-2.8.0 pyzmq-18.0.1 six-1.12.0 tornado-6.0.2 traitlets-4.3.2 wcwidth-0.1.7

$ pytest ipykernel
============================= test session starts ==============================
platform linux -- Python 3.8.0a3, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
rootdir: .../ipykernel
plugins: cov-2.6.1
collected 66 items / 3 errors / 63 selected

==================================== ERRORS ====================================
__________ ERROR collecting ipykernel/inprocess/tests/test_kernel.py ___________
ipykernel/inprocess/tests/test_kernel.py:13: in <module>
    from IPython.testing.decorators import skipif_not_matplotlib
__venv38__/lib64/python3.8/site-packages/IPython/testing/decorators.py:336: in <module>
    skip_known_failure = dec.knownfailureif(True,'This test is known to fail')
E   NameError: name 'dec' is not defined
_______________ ERROR collecting ipykernel/tests/test_kernel.py ________________
ipykernel/tests/test_kernel.py:15: in <module>
    from IPython.testing import decorators as dec, tools as tt
__venv38__/lib64/python3.8/site-packages/IPython/testing/decorators.py:336: in <module>
    skip_known_failure = dec.knownfailureif(True,'This test is known to fail')
E   NameError: name 'dec' is not defined
______________ ERROR collecting ipykernel/tests/test_serialize.py ______________
ipykernel/tests/test_serialize.py:10: in <module>
    from IPython.testing import decorators as dec
__venv38__/lib64/python3.8/site-packages/IPython/testing/decorators.py:336: in <module>
    skip_known_failure = dec.knownfailureif(True,'This test is known to fail')
E   NameError: name 'dec' is not defined
=============================== warnings summary ===============================
ipykernel/pickleutil.py:8
  .../ipykernel/ipykernel/pickleutil.py:8: DeprecationWarning: ipykernel.pickleutil is deprecated. It has moved to ipyparallel.
    warnings.warn("ipykernel.pickleutil is deprecated. It has moved to ipyparallel.", DeprecationWarning)

ipykernel/codeutil.py:17
  .../ipykernel/ipykernel/codeutil.py:17: DeprecationWarning: ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize
    warnings.warn("ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize", DeprecationWarning)

ipykernel/serialize.py:7
  .../ipykernel/ipykernel/serialize.py:7: DeprecationWarning: ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize
    warnings.warn("ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
===================== 3 warnings, 3 error in 1.04 seconds ======================

$ pip install nose-warnings-filters
...
Successfully installed nose-warnings-filters-0.1.5

$ nosetests ipykernel
.../ipykernel/ipykernel/pickleutil.py:8: DeprecationWarning: ipykernel.pickleutil is deprecated. It has moved to ipyparallel.
  warnings.warn("ipykernel.pickleutil is deprecated. It has moved to ipyparallel.", DeprecationWarning)
.../ipykernel/ipykernel/codeutil.py:17: DeprecationWarning: ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize
  warnings.warn("ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize", DeprecationWarning)
.../ipykernel/ipykernel/serialize.py:7: DeprecationWarning: ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize
  warnings.warn("ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize", DeprecationWarning)
E.../ipykernel/ipykernel/datapub.py:5: DeprecationWarning: ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub
  warnings.warn("ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub", DeprecationWarning)
.../ipykernel/ipykernel/iostream.py:66: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  self.io_loop = IOLoop(make_current=False)
......E............E............---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-2-9e1622b385b6> in <module>
----> 1 1/0

ZeroDivisionError: division by zero
.........................E........
======================================================================
ERROR: Failure: NameError (name 'dec' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 777, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../ipykernel/ipykernel/inprocess/tests/test_kernel.py", line 13, in <module>
    from IPython.testing.decorators import skipif_not_matplotlib
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/IPython/testing/decorators.py", line 336, in <module>
    skip_known_failure = dec.knownfailureif(True,'This test is known to fail')
NameError: name 'dec' is not defined

======================================================================
ERROR: ipykernel.tests.test_async.test_async_interrupt
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_async_interrupt() missing 2 required positional arguments: 'asynclib' and 'request'

======================================================================
ERROR: Failure: NameError (name 'dec' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 777, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../ipykernel/ipykernel/tests/test_kernel.py", line 15, in <module>
    from IPython.testing import decorators as dec, tools as tt
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/IPython/testing/decorators.py", line 336, in <module>
    skip_known_failure = dec.knownfailureif(True,'This test is known to fail')
NameError: name 'dec' is not defined

======================================================================
ERROR: Failure: NameError (name 'dec' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 777, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".../ipykernel/ipykernel/tests/test_serialize.py", line 10, in <module>
    from IPython.testing import decorators as dec
  File ".../ipykernel/__venv38__/lib64/python3.8/site-packages/IPython/testing/decorators.py", line 336, in <module>
    skip_known_failure = dec.knownfailureif(True,'This test is known to fail')
NameError: name 'dec' is not defined

----------------------------------------------------------------------
Ran 67 tests in 24.837s

FAILED (errors=4)

$ pip freeze
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
coverage==5.0a4
decorator==4.4.0
ipykernel==5.2.0.dev0
ipython==7.4.0
ipython-genutils==0.2.0
jedi==0.13.3
jupyter-client==5.2.4
jupyter-core==4.4.0
more-itertools==7.0.0
nose==1.3.7
nose-warnings-filters==0.1.5
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
pluggy==0.9.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
py==1.8.0
Pygments==2.3.1
pytest==4.4.0
pytest-cov==2.6.1
python-dateutil==2.8.0
pyzmq==18.0.1
six==1.12.0
tornado==6.0.2
traitlets==4.3.2
wcwidth==0.1.7
```

Travis Ci seems to handle this just fine. What am I missing?

**Comment by hroncok** [comment]
Oh. So I think I found the issue...

**Comment by hroncok** [comment]
When numpy is installed, this imports `dec` from it:

https://github.com/ipython/ipython/blob/4f901de17aff2132365fc3741fc5b4b8a9a98dc6/IPython/external/decorators/__init__.py#L3

Such dec has `knownfailureif`.

```pycon
>>> from numpy.testing import dec
>>> hasattr(dec, 'knownfailureif')
True
```

If numpy is not installed, everythin from `_decorators` is imported instead: https://github.com/ipython/ipython/blob/4f901de17aff2132365fc3741fc5b4b8a9a98dc6/IPython/external/decorators/__init__.py#L6

It has direct `knownfailureif`, no `dec`:

```
>>> from IPython.external.decorators import _decorators
>>> hasattr(_decorators, 'dec')
False
>>> hasattr(_decorators, 'knownfailureif')
True
```

**Comment by hroncok** [comment]
```patch
--- IPython/external/decorators/__init__.py 2019-04-09 13:25:15.521858290 +0200
+++ IPython/external/decorators/__init__.py.new     2019-04-09 13:25:12.922839115 +0200
@@ -4,6 +4,7 @@
     from numpy.testing.noseclasses import KnownFailure
 except ImportError:
     from ._decorators import *
+    from . import _decorators as dec
     try:
         from ._numpy_testing_noseclasses import KnownFailure
     except ImportError:
```

Kinda workarounds this, but is very ugly.
