### ISSUE TITLE
Jupyter Notebook, The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by insgong** [ipython/ipykernel#418]

**Comment by willingc** [comment]
@insgong Did you have additional information that you wish to provide? Often this message gets displayed if the kernel is not properly installed to work with the notebook.

**Comment by HamdiB1** [comment]
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\ProgramData\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 310, in main
kernel.start()
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelapp.py", line 477, in start
ioloop.IOLoop.instance().start()
File "C:\ProgramData\Anaconda3\lib\site‑packages\tornado\platform\asyncio.py", line 148, in start
self.asyncio_loop.run_forever()
File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 526, in run_forever
raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 438, in _run_callback
callback(*args, **kwargs)
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "C:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 456, in _handle_events
self._handle_recv()
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 486, in _handle_recv
self._run_callback(callback, msg)
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 438, in _run_callback
callback(*args, **kwargs)
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "C:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback functools.partial(. at 0x00000230798E59D8>)
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site‑packages\tornado\ioloop.py", line 743, in _run_callback
ret = callback()
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 542, in 
self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 456, in _handle_events
self._handle_recv()
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 486, in _handle_recv
self._run_callback(callback, msg)
File "C:\ProgramData\Anaconda3\lib\site‑packages\zmq\eventloop\zmqstream.py", line 438, in _run_callback
callback(*args, **kwargs)
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
self.pre_handler_hook()
File "C:\Users\h4mdi\AppData\Roaming\Python\Python37\site‑packages\ipykernel\kernelbase.py", line 248, in pre_handler_hook
self.saved_sigint_handler = signal(SIGINT, default_int_handler)
File "C:\ProgramData\Anaconda3\lib\signal.py", line 47, in signal
handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

**Comment by MSeal** [comment]
> ValueError: signal only works in main thread

Looks like your kernel was launched inside another thread or async loop. Since the ipykernel uses async patterns it needs to be launched within it's own thread. A way to circumvent this if you have to is to launch subprocesses that are running the kernel process (this is what jupyter_client does).
