### ISSUE TITLE
IPykernel broken on Python 2.7

### ISSUE THREAD

**Issue by matthew-brett** [ipython/ipykernel#424]
As of today, `pip install ipykernel` in a fresh 2.7 virtualenv gives:

```
Building wheels for collected packages: ipykernel, tornado
  Building wheel for ipykernel (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/brettmz-admin/.virtualenvs/test/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/2z/3z9jy4411qj2b_pmmt5fm64h0000gq/T/pip-install-fwgfaB/ipykernel/setup.py'"'"'; __file__='"'"'/private/var/folders/2z/3z9jy4411qj2b_pmmt5fm64h0000gq/T/pip-install-fwgfaB/ipykernel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/2z/3z9jy4411qj2b_pmmt5fm64h0000gq/T/pip-wheel-68G1Fp --python-tag cp27
       cwd: /private/var/folders/2z/3z9jy4411qj2b_pmmt5fm64h0000gq/T/pip-install-fwgfaB/ipykernel/
  Complete output (9 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/2z/3z9jy4411qj2b_pmmt5fm64h0000gq/T/pip-install-fwgfaB/ipykernel/setup.py", line 91, in <module>
      from ipykernel.kernelspec import write_kernel_spec, make_ipkernel_cmd, KERNEL_NAME
    File "ipykernel/__init__.py", line 2, in <module>
      from .connect import *
    File "ipykernel/connect.py", line 13, in <module>
      from IPython.core.profiledir import ProfileDir
  ImportError: No module named IPython.core.profiledir
  ----------------------------------------
  ERROR: Failed building wheel for ipykernel
```

See: https://travis-ci.org/matthew-brett/nb2plots/jobs/569749928#L472 for a Travis CI log of same.

**Comment by ccordoba12** [comment]
@blink1073, you forgot to upload wheels for Python 2 to PyPI (there are wheels for Python 3 only).

**Comment by blink1073** [comment]
Hmm, bdist_wheel only produced the py3 wheel.  It has been a while, does anyone know how to get the py2 wheel?  Do I need to run bdist_wheel from a py27 conda env?

**Comment by ccordoba12** [comment]
> Do I need to run bdist_wheel from a py27 conda env?

Yep, that should make the trick.

**Comment by blink1073** [comment]
Done: `Uploading ipykernel-4.10.1-py2-none-any.whl`

**Comment by blink1073** [comment]
@matthew-brett, can you please confirm the fix?

**Comment by matthew-brett** [comment]
Thanks - yes - fixed now: https://travis-ci.org/matthew-brett/nb2plots/builds/569749922

**Comment by blink1073** [comment]
Great, thanks @matthew-brett and @ccordoba12!
