### ISSUE TITLE
5 tests fail

### ISSUE THREAD

**Issue by piccolbo** [ipython/ipykernel#436]
I performed the install as per contributing guidelines (editable). When I run nosetests I get 5 errors + 1 skipped. Python 3.6, Mojave 10.14.6, ipykernel just updated from master. Full logs below. Suggestions?

```
antonio@MacBook-Pro-4 ~/P/o/ipykernel> nosetests ipykernel 
/Users/antonio/Projects/others/ipykernel/ipykernel/pickleutil.py:8: DeprecationWarning: ipykernel.pickleutil is deprecated. It has moved to ipyparallel.
  warnings.warn("ipykernel.pickleutil is deprecated. It has moved to ipyparallel.", DeprecationWarning)
/Users/antonio/Projects/others/ipykernel/ipykernel/codeutil.py:17: DeprecationWarning: ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize
  warnings.warn("ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize", DeprecationWarning)
/Users/antonio/Projects/others/ipykernel/ipykernel/serialize.py:7: DeprecationWarning: ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize
  warnings.warn("ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize", DeprecationWarning)
/Users/antonio/Projects/others/ipykernel/ipykernel/datapub.py:5: DeprecationWarning: ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub
  warnings.warn("ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub", DeprecationWarning)
/Users/antonio/Projects/others/ipykernel/ipykernel/iostream.py:66: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  self.io_loop = IOLoop(make_current=False)
/Users/antonio/Projects/others/ipykernel/ipykernel/inprocess/tests/test_kernel.py:76: UserWarning: The `stream` parameter of `getpass.getpass` will have no effect when using ipykernel
  kernel.getpass(stream='non empty')
.........EE..EEE.....................S.......Assertion failed: rc == 0 (src/socket_poller.cpp:41)
.............---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-119-9e1622b385b6> in <module>()
----> 1 1/0

ZeroDivisionError: division by zero
...............................................
======================================================================
ERROR: ipykernel.tests.test_async.test_async_await
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antonio/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/antonio/Projects/others/ipykernel/ipykernel/tests/test_async.py", line 37, in test_async_await
    flush_channels(KC)
  File "/Users/antonio/Projects/others/ipykernel/ipykernel/tests/utils.py", line 50, in flush_channels
    for channel in (kc.shell_channel, kc.iopub_channel):
AttributeError: 'NoneType' object has no attribute 'shell_channel'
-------------------- >> begin captured logging << --------------------
traitlets: DEBUG: Installing kernelspec in /private/var/folders/_p/1gx4vy311_x4syn2xq6f2xtc0000gr/T/tmp6jf3qsyk/Library/Jupyter/kernels/python3
traitlets: INFO: Installed kernelspec python3 in /private/var/folders/_p/1gx4vy311_x4syn2xq6f2xtc0000gr/T/tmp6jf3qsyk/Library/Jupyter/kernels/python3
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: ipykernel.tests.test_async.test_async_interrupt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antonio/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_async_interrupt() missing 2 required positional arguments: 'asynclib' and 'request'

======================================================================
ERROR: ipykernel.tests.test_connect.test_port_bind_failure_raises
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antonio/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_port_bind_failure_raises() missing 1 required positional argument: 'request'

======================================================================
ERROR: ipykernel.tests.test_connect.test_port_bind_failure_recovery
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antonio/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_port_bind_failure_recovery() missing 1 required positional argument: 'request'

======================================================================
ERROR: ipykernel.tests.test_connect.test_port_bind_failure_gives_up_retries
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/antonio/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: test_port_bind_failure_gives_up_retries() missing 1 required positional argument: 'request'

----------------------------------------------------------------------
Ran 105 tests in 33.421s

FAILED (SKIP=1, errors=5)
```

**Comment by veprbl** [comment]
I see the same issue also on macOS. Running tests via `pytest` seems to not have this problem.

**Comment by ogencoglu** [comment]
Same here! Any insights on this?
