### ISSUE TITLE
ZMQInteractiveShell does not run post_execute and post_run_cell events on async cells

### ISSUE THREAD

**Issue by JoaoFelipe** [ipython/ipykernel#520]
In the notebook repository, I submitted an issue indicating that some cells did not display matplotlib images and delayed their display to the next cell (https://github.com/jupyter/notebook/issues/5568). After some inspection, I noticed that it only occurs in Python >= 3.8 and that the code elements that cause the issue are comprehensions, which are being detected by IPython as async cells. So, I submitted another issue to the IPython repository related to the misdetection (https://github.com/ipython/ipython/issues/12422).

However, async cells should not prevent matplotlib from displaying in the right cells after the end of their executions. I inspected it further and realized that the problem with async cells is that they do not run `post_execute` and `post_run_cell` events.

Here is a small example with the bug that does not use comprehensions nor matplotib (so it is easier to create a test and if someone fixes the async detection in the IPython repository, it will not impact this bug report):

**In [1]:**
```python
COUNTER = 0
def count():
    global COUNTER
    COUNTER += 1
    print("Count", COUNTER)
ip = get_ipython()
ip.events.register('post_execute', count)
print('A')
```
A
Count 1

**In [2]:**
```python
import asyncio
await asyncio.sleep(0)
print('B')
```
B

**In [3]:**
```python
print('C')
```
C
Count 2

---------------------------------------------
I'm pretty sure this is the main cause of the bug that I reported in the notebook repository (https://github.com/jupyter/notebook/issues/5568). Should I close the issue there now or wait for a fix of the bug here?

This issue is also related to #514

**Comment by JoaoFelipe** [comment]
I'm not sure this is the right fix, but I could "fix" it by replacing https://github.com/ipython/ipykernel/blob/master/ipykernel/ipkernel.py#L295 by
```python
                    res = None
                    try:
                        res = yield coro_future
                    finally:
                        shell.events.trigger('post_execute')
                        if not silent:
                            shell.events.trigger('post_run_cell', res)
```

I took this code from https://github.com/ipython/ipython/blob/d14c35c0d1d842f3286c2b33beb049291be09193/IPython/core/interactiveshell.py#L2864-L2871

Should I submit a pull request with this fix? The async tests are failing here (even before the change), so I'm not very confident.

**Comment by blink1073** [comment]
@JoaoFelipe your proposed patch seems reasonable.  Where are you seeing test failures?  The latest CI looks good: https://travis-ci.org/github/ipython/ipykernel/builds/702553175

**Comment by JoaoFelipe** [comment]
In my machine:
```
/home/joao/projects/ipykernel/ipykernel/pickleutil.py:8: DeprecationWarning: ipykernel.pickleutil is deprecated. It has moved to ipyparallel.
  warnings.warn("ipykernel.pickleutil is deprecated. It has moved to ipyparallel.", DeprecationWarning)
/home/joao/projects/ipykernel/ipykernel/codeutil.py:17: DeprecationWarning: ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize
  warnings.warn("ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize", DeprecationWarning)
/home/joao/projects/ipykernel/ipykernel/serialize.py:7: DeprecationWarning: ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize
  warnings.warn("ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize", DeprecationWarning)
/home/joao/projects/ipykernel/ipykernel/datapub.py:5: DeprecationWarning: ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub
  warnings.warn("ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub", DeprecationWarning)
/home/joao/projects/ipykernel/ipykernel/iostream.py:66: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  self.io_loop = IOLoop(make_current=False)
/home/joao/projects/ipykernel/ipykernel/inprocess/tests/test_kernel.py:110: UserWarning: The `stream` parameter of `getpass.getpass` will have no effect when using ipykernel
  kernel.getpass(stream='non empty')
.........EE..EEE..../home/joao/anaconda3/envs/raw38/lib/python3.8/site-packages/jupyter_client/manager.py:357: FutureWarning: Method cleanup(connection_file=True) is deprecated, use cleanup_resources(restart=False).
  warnings.warn("Method cleanup(connection_file=True) is deprecated, use cleanup_resources(restart=False).",
.................S....S..S...............---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-118-9e1622b385b6> in <module>
----> 1 1/0

ZeroDivisionError: division by zero
............................./home/joao/projects/ipykernel/ipykernel/tests/test_serialize.py:72: DeprecationWarning: Importing from numpy.testing.utils is deprecated since 1.15.0, import from numpy.testing instead.
  from numpy.testing.utils import assert_array_equal
..................
======================================================================
ERROR: ipykernel.tests.test_async.test_async_await
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joao/anaconda3/envs/raw38/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/joao/projects/ipykernel/ipykernel/tests/test_async.py", line 37, in test_async_await
    flush_channels(KC)
  File "/home/joao/projects/ipykernel/ipykernel/tests/utils.py", line 50, in flush_channels
    for channel in (kc.shell_channel, kc.iopub_channel):
AttributeError: 'NoneType' object has no attribute 'shell_channel'
-------------------- >> begin captured logging << --------------------
traitlets: DEBUG: Installing kernelspec in /tmp/tmpjz7l170d/.local/share/jupyter/kernels/python3
traitlets: INFO: Installed kernelspec python3 in /tmp/tmpjz7l170d/.local/share/jupyter/kernels/python3
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: ipykernel.tests.test_async.test_async_interrupt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joao/anaconda3/envs/raw38/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_async_interrupt() missing 2 required positional arguments: 'asynclib' and 'request'

======================================================================
ERROR: ipykernel.tests.test_connect.test_port_bind_failure_raises
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joao/anaconda3/envs/raw38/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_port_bind_failure_raises() missing 1 required positional argument: 'request'

======================================================================
ERROR: ipykernel.tests.test_connect.test_port_bind_failure_recovery
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joao/anaconda3/envs/raw38/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_port_bind_failure_recovery() missing 1 required positional argument: 'request'

======================================================================
ERROR: ipykernel.tests.test_connect.test_port_bind_failure_gives_up_retries
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joao/anaconda3/envs/raw38/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_port_bind_failure_gives_up_retries() missing 1 required positional argument: 'request'

----------------------------------------------------------------------
Ran 108 tests in 28.370s

FAILED (SKIP=3, errors=5)
```
Anyway, I submitted a pull request (of course without new tests, since they are not working here). Let's see if CI works
