### ISSUE TITLE
ipykernel 5.0+ with python 3.6, use asyncio with ThreadPoolExecutor meet error "RuntimeError: Event loop is closed"

### ISSUE THREAD

**Issue by martin-liu** [ipython/ipykernel#534]
Below code works with python 3.6 and ipykernel 4.x (tested 4.10.1), but will fail with ipykernel 5.0+

pseudo code:
```python
loop = asyncio.new_event_loop()

data = []
      
for status in statuses:
    data.append(
        loop.run_until_complete(_download_parallel(loop, status))
    )

loop.close()
```

`_download_parallel` is something like:
```python
async def _download_parallel(loop, status):
    futures = []
    for headers in status:
        future = loop.run_in_executor(getIoExecutor(), lambda: _do_download(headers))
    return await asyncio.gather(*futures, loop)
```

Error info:
```
07/29/2020 21:13:08 ERROR:tornado.general Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 404, in schedule_dispatch
    args,
  File "/opt/conda/lib/python3.6/site-packages/tornado/queues.py", line 200, in put_nowait
    future_set_result_unless_cancelled(getter, self._get())
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 627, in future_set_result_unless_cancelled
    future.set_result(value)
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 591, in call_soon
    self._check_closed()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
07/29/2020 21:13:08 ERROR:tornado.general Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 404, in schedule_dispatch
    args,
  File "/opt/conda/lib/python3.6/site-packages/tornado/queues.py", line 200, in put_nowait
    future_set_result_unless_cancelled(getter, self._get())
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 627, in future_set_result_unless_cancelled
    future.set_result(value)
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 591, in call_soon
    self._check_closed()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
07/29/2020 21:13:08 ERROR:asyncio Exception in callback BaseAsyncIOLoop._handle_events(15, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(15, 1)>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/opt/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/opt/conda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 404, in schedule_dispatch
    args,
  File "/opt/conda/lib/python3.6/site-packages/tornado/queues.py", line 200, in put_nowait
    future_set_result_unless_cancelled(getter, self._get())
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 627, in future_set_result_unless_cancelled
    future.set_result(value)
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 591, in call_soon
    self._check_closed()
  File "/opt/conda/lib/python3.6/asyncio/base_events.py", line 377, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed 
```

**Comment by martin-liu** [comment]
For this issue, it was because another library `nest-asyncio` v1.3.x which only works with ipykernel 4.x, upgrade `nest-asyncio` to 1.4.0 solved the issue.
