### ISSUE TITLE
AttributeError: module 'pickle' has no attribute 'DEFAULT_PROTOCOL'

### ISSUE THREAD

**Issue by johentsch** [ipython/ipykernel#549]
Hello folks,

I think my problem is a very peculiar one and I am not sure whether the problem lies in ipykernel: The error occurs in zqm, where [I have filed the same issue report](https://github.com/zeromq/pyzmq/issues/1428), but it is closely linked to `ipykernel`.

The story goes like this: I was coding in Atom using ipykernels. Specifically, I was trying to pickle a difficult object with `dill` and `pickle` modules, simply applying the method `dumps()`. The objects had unpicklable objects so the kernel died several times and I had to restart it. But at some point it did not restart, instead, with every trial, I got this:
```
Traceback (most recent call last):
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/socket.py", line 38, in <module>
    DEFAULT_PROTOCOL = pickle.DEFAULT_PROTOCOL
AttributeError: module 'pickle' has no attribute 'DEFAULT_PROTOCOL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hentsche/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hentsche/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/__init__.py", line 49, in <module>
    from zmq import sugar
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/__init__.py", line 7, in <module>
    from zmq.sugar import (
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/context.py", line 20, in <module>
    from .socket import Socket
  File "/home/hentsche/anaconda3/lib/python3.8/site-packages/zmq/sugar/socket.py", line 40, in <module>
    DEFAULT_PROTOCOL = pickle.HIGHEST_PROTOCOL
```

But what is even more surprising: That happened on my old Anaconda installation with Python 3.7 (same error, just with python3.7 in the path): That one I have removed completely and installed a completely fresh Anaconda with Python 3.8. The problem persisted in Atom, so I fired up my Jupyter Lab and here comes the best part: One of my existing notebooks works as usual, but any other - including a completely new one - does not manage to start a kernel and the error message is the same! I have also tried with a new kernel in a new conda environment.

Let me know if more information is needed and thanks for your help.

**Comment by minrk** [comment]
What do you get for `python -c 'import pickle; print(pickle)'`? This sounds like perhaps the stdlib `pickle` module has been overridden, e.g. by a `pickle.py` file or `pickle` folder in the current directory because this AttributeError will not happen with the actual stdlib pickle module.

**Comment by johentsch** [comment]
The result looks correct:
`<module 'pickle' from '/home/hentsche/anaconda3/lib/python3.8/pickle.py'>`
I don't know how to test is for the kernels because it happens while launching them. I am still perplexed by the fact that in one notebook it is actually working and there the result of `print(pickl)` is correct, too.

**Comment by minrk** [comment]
do you have any files called `pickle.py` or directories called `pickle`? Most likely in the same directory as the notebooks that don't work?

**Comment by johentsch** [comment]
Bingo, that's the solution! There are a lot of things in the `tmp` folder, also a file called `pickle.py`. Thank you very much!
