### ISSUE TITLE
Import issue: AttributeError: 'NoneType' object has no attribute 'session'

### ISSUE THREAD

**Issue by MislavSag** [ipython/ipykernel#552]
When import the package inside VScode I get an error:
```
<IPython.core.display.Javascript object>
<IPython.core.display.HTML object>
Traceback (most recent call last):
  File ".\dpseg.py", line 379, in <module>
    run()
  File ".\dpseg.py", line 320, in run
    cerebro.plot()
  File "C:\ProgramData\Anaconda3\lib\site-packages\backtrader\cerebro.py", line 996, in plot
    plotter.show()
  File "C:\ProgramData\Anaconda3\lib\site-packages\backtrader\plot\plot.py", line 817, in show
    self.mpyplot.show()
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\pyplot.py", line 272, in show
    return _show(*args, **kw)
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_nbagg.py", line 261, in show
    manager.show()
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_nbagg.py", line 90, in show
    self._create_comm()
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_nbagg.py", line 122, in _create_comm
    self.add_web_socket(comm)
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_webagg_core.py", line 433, in add_web_socket
    self.resize(w, h)
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_webagg_core.py", line 417, in resize
    self._send_event(
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_webagg_core.py", line 490, in _send_event
    s.send_json(payload)
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_nbagg.py", line 199, in send_json
    self.comm.send({'data': json.dumps(content)})
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\ipykernel\comm\comm.py", line 122, in send
    self._publish_msg('comm_msg',
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\ipykernel\comm\comm.py", line 66, in _publish_msg
    self.kernel.session.send(self.kernel.iopub_socket, msg_type,
AttributeError: 'NoneType' object has no attribute 'session'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\_pylab_helpers.py", line 72, in destroy_all
    manager.destroy()
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_nbagg.py", line 126, in destroy
    self._send_event('close')
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_webagg_core.py", line 490, in _send_event
    s.send_json(payload)
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\matplotlib\backends\backend_nbagg.py", line 199, in send_json
    self.comm.send({'data': json.dumps(content)})
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\ipykernel\comm\comm.py", line 122, in send
    self._publish_msg('comm_msg',
  File "C:\Users\Mislav\AppData\Roaming\Python\Python38\site-packages\ipykernel\comm\comm.py", line 66, in _publish_msg
    self.kernel.session.send(self.kernel.iopub_socket, msg_type,
AttributeError: 'NoneType' object has no attribute 'session'
```
I have found similar issue few years old, but I don't understand what is the solution to this. It is mentioning jupyter notebook. Do I have to use this package only inside jupyter?

**Comment by NoraGithub** [comment]
is it fixed? @martinRenou

**Comment by kerenb-vayyar** [comment]
This is still an issue I'm facing, doesn't look like it got fixed.

**Comment by martinRenou** [comment]
@kerenb-vayyar which ipykernel version are you using? Can you try with the very latest version if you're not using it already?

**Comment by kerenb-vayyar** [comment]
I'm not using jupyter, I'm using pycharm. I fixed it by adding the interactive matplotlib.pyplot option inside the script of figure.py

**Comment by Zoe-FW** [comment]
> I'm not using jupyter, I'm using pycharm. I fixed it by adding the interactive matplotlib.pyplot option inside the script of figure.py, under 'if restore_to_pylab:'

I am using pycharm too, may I ask how did you 'adding the interactive matplotlib.pyplot option'?

below is how it currently looks like:
![image](https://github.com/ipython/ipykernel/assets/53399983/d720bcf5-656f-4346-811c-b150c172cd84)
