### ISSUE TITLE
TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'

### ISSUE THREAD

**Issue by o-smirnov** [ipython/ipykernel#621]
Getting this error trying to execute any notebook cell with 5.5.2:
```
radiopadre.client: oleg@iglesia stderr: [IPKernelApp] ERROR | Exception in message handler:
radiopadre.client: oleg@iglesia stderr: Traceback (most recent call last):
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
radiopadre.client: oleg@iglesia stderr:     yield gen.maybe_future(handler(stream, idents, msg))
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
radiopadre.client: oleg@iglesia stderr:     value = future.result()
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/tornado/gen.py", line 769, in run
radiopadre.client: oleg@iglesia stderr:     yielded = self.gen.throw(*exc_info)  # type: ignore
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 538, in execute_request
radiopadre.client: oleg@iglesia stderr:     user_expressions, allow_stdin,
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/tornado/gen.py", line 762, in run
radiopadre.client: oleg@iglesia stderr:     value = future.result()
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
radiopadre.client: oleg@iglesia stderr:     yielded = ctx_run(next, result)
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
radiopadre.client: oleg@iglesia stderr:     return f(*args, **kw)
radiopadre.client: oleg@iglesia stderr:   File "/home/oleg/.radiopadre/venv/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 290, in do_execute
radiopadre.client: oleg@iglesia stderr:     and should_run_async(code, transformed_cell=transformed_cell, preprocessing_exc_tuple=preprocessing_exc_tuple)
radiopadre.client: oleg@iglesia stderr: TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'
radiopadre.client: oleg@iglesia stderr: [IPKernelApp] ERROR | Exception in message handler:
```

Problem goes away with ``pip install "ipykernel<5.5.2"``.

**Comment by blink1073** [comment]
Yikes, apologies, this was related to the failed 5.5.1 release, cf https://github.com/ipython/ipykernel/issues/607.  We'll have to sort this out and make a 5.5.3 release tomorrow.

**Comment by needhamj** [comment]
Reopening this issue with 6.6.1.
`Traceback (most recent call last):
 File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 353, in dispatch_shell
 await result
 File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 648, in execute_request
  reply_content = await reply_content
 File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 326, in do_execute
  and should_run_async(
 TypeError: should_run_async() got an unexpected keyword argument 'transformed_cell'`

**Comment by nasserboan** [comment]
Havin this problem with 6.6.1 =(
