### ISSUE TITLE
IPykernel Debugger

### ISSUE THREAD

**Issue by mlucool** [ipython/ipykernel#629]
Hi,

I tried `6.0.0a2` and found that while I could add breakpoints, variables did not appear.

![image](https://user-images.githubusercontent.com/1813603/113604580-7962df80-9613-11eb-8443-551a84ec226a.png)

The server has the following error:
```
Traceback (most recent call last):
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/debugger.py", line 327, in stackTrace
    module_idx = len(sf_list) - next(i for i, v in enumerate(reversed(sf_list), 1) if v['name'] == '<module>' and i != 1)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/kernelbase.py", line 217, in process_control
    yield gen.maybe_future(handler(self.control_stream, idents, msg))
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/kernelbase.py", line 729, in debug_request
    reply_content = yield gen.maybe_future(self.do_debug_request(content))
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/ipkernel.py", line 410, in do_debug_request
    return (yield self.debugger.process_request(msg))
  File "/path/to/myvenv/lib64/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/path/to/myvenv/lib64/python3.7/site-packages/ipykernel/debugger.py", line 455, in process_request
    reply = await handler(message)
RuntimeError: coroutine raised StopIteration
```

**Comment by JohanMabille** [comment]
Hi,

It's weird that the line of the breakpoint is not highlighted on your screenshot. I failed to reproduce with last Jupyterlab, ipykernel 6.0.0a2 and python 3.7.10:

![ipykernel_no_variables](https://user-images.githubusercontent.com/6754742/114285365-dc5ed700-9a56-11eb-8e0c-c4ca224d64bf.gif)

Can you list all the packages installed?

**Comment by mlucool** [comment]
Thanks for looking into this. I confirmed I also get this error on a different unrelated python setup.
Steps:
```
python -m venv myvenv 
source myvenv/bin/activate
pip install jupyterlab ipykernel==6.0.0a2
./myvenv/bin/jupyter-lab
```

Packages:
```
 % ./myvenv/bin/jupyter troubleshoot
You are using pip version 19.0.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$PATH:
	/path/to/myvenv/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/sbin
	/sbin

sys.path:
	/path/to/myvenv/bin
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python37.zip
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7
	/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/lib-dynload
	/path/to/myvenv/lib/python3.7/site-packages

sys.executable:
	/path/to/myvenv/bin/python3

sys.version:
	3.7.3 (default, Apr 24 2020, 18:51:23) 
	[Clang 11.0.3 (clang-1103.0.32.62)]

platform.platform():
	Darwin-20.3.0-x86_64-i386-64bit

which -a jupyter:
	/path/to/myvenv/bin/jupyter

pip list:
	Package             Version  
	------------------- ---------
	anyio               2.2.0    
	appnope             0.1.2    
	argon2-cffi         20.1.0   
	async-generator     1.10     
	attrs               20.3.0   
	Babel               2.9.0    
	backcall            0.2.0    
	bleach              3.3.0    
	certifi             2020.12.5
	cffi                1.14.5   
	chardet             4.0.0    
	debugpy             1.2.1    
	decorator           5.0.6    
	defusedxml          0.7.1    
	entrypoints         0.3      
	idna                2.10     
	importlib-metadata  3.10.0   
	ipykernel           6.0.0a2  
	ipython             7.22.0   
	ipython-genutils    0.2.0    
	jedi                0.18.0   
	Jinja2              2.11.3   
	json5               0.9.5    
	jsonschema          3.2.0    
	jupyter-client      6.1.13   
	jupyter-core        4.7.1    
	jupyter-packaging   0.7.12   
	jupyter-server      1.6.0    
	jupyterlab          3.0.13   
	jupyterlab-pygments 0.1.2    
	jupyterlab-server   2.4.0    
	MarkupSafe          1.1.1    
	mistune             0.8.4    
	nbclassic           0.2.7    
	nbclient            0.5.3    
	nbconvert           6.0.7    
	nbformat            5.1.3    
	nest-asyncio        1.5.1    
	notebook            6.3.0    
	packaging           20.9     
	pandocfilters       1.4.3    
	parso               0.8.2    
	pexpect             4.8.0    
	pickleshare         0.7.5    
	pip                 19.0.3   
	prometheus-client   0.10.1   
	prompt-toolkit      3.0.18   
	ptyprocess          0.7.0    
	pycparser           2.20     
	Pygments            2.8.1    
	pyparsing           2.4.7    
	pyrsistent          0.17.3   
	python-dateutil     2.8.1    
	pytz                2021.1   
	pyzmq               22.0.3   
	requests            2.25.1   
	Send2Trash          1.5.0    
	setuptools          40.8.0   
	six                 1.15.0   
	sniffio             1.2.0    
	terminado           0.9.4    
	testpath            0.4.4    
	tornado             6.1      
	traitlets           5.0.5    
	typing-extensions   3.7.4.3  
	urllib3             1.26.4   
	wcwidth             0.2.5    
	webencodings        0.5.1    
	zipp                3.4.1
```

**Comment by JohanMabille** [comment]
Everything looks correct regarding the package.

Do you have the opportunity to install this [test branch](https://github.com/JohanMabille/ipykernel/tree/debug_osx) of ipykernel and run your code again? If so, you should see an array printed above the cell after executing it, can you copy - paste it here?

**Comment by mlucool** [comment]
Upgrading to that branch made the debugger work in the UI.

Upgrade:
```
pip install git+https://github.com/JohanMabille/ipykernel.git@debug_osx
...
Successfully built ipykernel
Installing collected packages: ipykernel
  Found existing installation: ipykernel 6.0.0a2
    Uninstalling ipykernel-6.0.0a2:
      Successfully uninstalled ipykernel-6.0.0a2
Successfully installed ipykernel-6.0.0.dev0
```

Output:
```
[{'id': 4, 'name': 'foo', 'line': 2, 'column': 1, 'source': {'path': '/var/folders/3b/n_bntsp9125gxpzmng1fm07m0000gn/T/ipykernel_15664/2016374787.py', 'sourceReference': 0}}, {'id': 5, 'name': '<module>', 'line': 5, 'column': 1, 'source': {'path': '/var/folders/3b/n_bntsp9125gxpzmng1fm07m0000gn/T/ipykernel_15664/2016374787.py', 'sourceReference': 0}}]
```

As a note, while you called the branch `debug_osx`, my original try was on linux.

**Comment by JohanMabille** [comment]
> As a note, while you called the branch debug_osx, my original try was on linux.

I've ben misled by the platform log; interesting to know that this bug is not specific to MacOS.

The output you have (i.e. the stack frames *before* filtering) is actually what I have *after* filtering. In my cas, the stack trace goes back to process start, including all internal calls of ipykernel.

I will implement a "cargo-kulting" patch, but it would be nice to understand what is going on here. Out of curiosity, which python distribution do you use?

**Comment by mlucool** [comment]
```
$ python -V
Python 3.7.3
$ python -c 'import platform; print(platform.python_implementation())'
CPython
```
