### ISSUE TITLE
v6 error with breakpoint in function

### ISSUE THREAD

**Issue by fcollonval** [ipython/ipykernel#697]
The tested cell is:

```py
def add(a, b):
    c = a + b
    return c

add(3, 2)
```

with the breakpoint set at c = a + b.

Demo of the error - it is only happening when listing the variables without debugging (aka kernel state):

![bug_ipykernel](https://user-images.githubusercontent.com/8435071/123936770-cdbcf780-d995-11eb-84af-ac34d0925687.gif)

The error seen is:

```
[IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 280, in process_control
    await result
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 832, in debug_request
    reply_content = json_clean(reply_content)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 142, in json_clean
    out[str(k)] = json_clean(v)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 142, in json_clean
    out[str(k)] = json_clean(v)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 128, in json_clean
    return [json_clean(x) for x in obj]
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 128, in <listcomp>
    return [json_clean(x) for x in obj]
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 142, in json_clean
    out[str(k)] = json_clean(v)
  File "/home/fcollonval/miniconda3/envs/jlab-dev/lib/python3.9/site-packages/ipykernel/jsonutil.py", line 148, in json_clean
    raise ValueError("Can't clean for JSON: %r" % obj)
ValueError: Can't clean for JSON: <function add at 0x7f1efa2198b0>
```

Xref: https://github.com/jupyterlab/jupyterlab/issues/10502

**Comment by Carreau** [comment]
I can't test right now, but can you try the following patch to narrow down the problem?

```python
diff --git a/ipykernel/debugger.py b/ipykernel/debugger.py
index f3ea2a9..9e9c94c 100644
--- a/ipykernel/debugger.py
+++ b/ipykernel/debugger.py
@@ -456,12 +456,15 @@ class Debugger:
         handler = self.static_debug_handlers.get(message['command'], None)
         if handler is not None:
             reply = await handler(message)
+            assert isinstance(reply, dict), f"{handler=} {message=}"
         elif self.is_started:
             handler = self.started_debug_handlers.get(message['command'], None)
             if handler is not None:
                 reply = await handler(message)
+                assert isinstance(reply, dict), f"{handler=} {message=}"
             else:
                 reply = await self._forward_message(message)
+                assert isinstance(reply, dict), f"{message=}"

         if message['command'] == 'disconnect':
             self.stop()
```

**Comment by mlucool** [comment]
This seems very similar to https://github.com/ipython/ipykernel/issues/647.

**Comment by Carreau** [comment]
It seem indeed, I'll send a PRs the add some asserts, and improve some warnings and logging to narrow down where the issue comes from.

**Comment by fcollonval** [comment]
The assertion are not raised.

When stop on the breakpoint, the function is indeed listed.

It looks like that the error comes from the following line as the value may not be jsonable:

https://github.com/ipython/ipykernel/blob/13d92202ef1b2466538bf9044c1559d81fc866be/ipykernel/debugger.py#L422

> This seems very similar to #647.

Indeed it seems that the pointer variable to functions (or class in the mentioned issue) are not returning a valid displayable description.

> They may be other kind too.

**Comment by fcollonval** [comment]
Changing that 422 line to

```diff
- 'value': v,
+ 'value': str(v),
```

results in no more error. But I guess the real patch should be more advanced than that.

**Comment by Carreau** [comment]
Ah good catch. @JohanMabille I believe you wrote most of these and might be the most qualified to fix it.

**Comment by JohanMabille** [comment]
I will work on this tonight.
