### ISSUE TITLE
Error loading extension: beatrix_jupyterlab

### ISSUE THREAD

**Issue by jnissin** [ipython/ipykernel#922]
I am having some issues loading extensions when running `ipykernel` version `6.13.0`. I have checked my configuration files and ensured there are no extensions specified in the configuration files in `/root/.ipython/profile_default/ipython_kernel_config.py` and `/root/.ipython/profile_default/ipython_config.py`. However, when I run `python -m ipykernel --debug` I get several errors regarding extension loading:

```
python -m ipykernel --debug
[IPKernelApp] IPYTHONDIR set to: /root/.ipython
[IPKernelApp] Using existing profile dir: '/root/.ipython/profile_default'
[IPKernelApp] Searching path ['/root/.ipython/profile_default', '/opt/conda/etc/ipython', '/usr/local/etc/ipython', '/etc/ipython'] for config files
[IPKernelApp] Attempting to load config file: ipython_config.py
[IPKernelApp] Looking for ipython_config in /etc/ipython
[IPKernelApp] Looking for ipython_config in /usr/local/etc/ipython
[IPKernelApp] Looking for ipython_config in /opt/conda/etc/ipython
[IPKernelApp] Looking for ipython_config in /root/.ipython/profile_default
[IPKernelApp] Loaded config file: /root/.ipython/profile_default/ipython_config.py
[IPKernelApp] Attempting to load config file: ipython_kernel_config.py
[IPKernelApp] Looking for ipython_kernel_config in /etc/ipython
[IPKernelApp] Loaded config file: /etc/ipython/ipython_kernel_config.py
[IPKernelApp] Looking for ipython_kernel_config in /usr/local/etc/ipython
[IPKernelApp] Looking for ipython_kernel_config in /opt/conda/etc/ipython
[IPKernelApp] Looking for ipython_kernel_config in /root/.ipython/profile_default
[IPKernelApp] Loaded config file: /root/.ipython/profile_default/ipython_kernel_config.py
[IPKernelApp] Connection file not found: kernel-4912.json
[IPKernelApp] Starting the kernel at pid: 4912
[IPKernelApp] shell ROUTER Channel on port: 45667
[IPKernelApp] stdin ROUTER Channel on port: 45033
[IPKernelApp] control ROUTER Channel on port: 42395
[IPKernelApp] iopub PUB Channel on port: 43247
[IPKernelApp] Heartbeat REP Channel on port: 48829
[IPKernelApp] Writing connection file: /root/.local/share/jupyter/runtime/kernel-4912.json
[IPKernelApp] To connect another client to this kernel, use:
[IPKernelApp]     --existing kernel-4912.json
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-4912.json
[IPKernelApp] Seeing logger to stderr, rerouting to raw filedescriptor.
[IPKernelApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?
[IPKernelApp] Loading IPython extensions...
[IPKernelApp] Loading IPython extension: storemagic
[IPKernelApp] Loading IPython extension: beatrix_jupyterlab
[IPKernelApp] WARNING | Error in loading extension: beatrix_jupyterlab
Check your config files in /root/.ipython/profile_default
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/shellapp.py", line 301, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/extensions.py", line 80, in load_extension
    mod = import_module(module_str)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'beatrix_jupyterlab'
[IPKernelApp] Loading IPython extension: google.cloud.bigquery
[IPKernelApp] WARNING | Error in loading extension: google.cloud.bigquery
Check your config files in /root/.ipython/profile_default
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/shellapp.py", line 301, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/extensions.py", line 81, in load_extension
    if mod.__file__.startswith(self.ipython_extension_dir):
AttributeError: 'NoneType' object has no attribute 'startswith'
[IPKernelApp] Loading IPython extension: sql
```

I can't locate where the extensions are specified to be loaded nor can I find any information regarding the extension `beatrix_jupyterlab`. Any information how to get rid of these errors or where I can find the configuration files attempting to load these extensions would be much appreciated.

**Comment by jnissin** [comment]
Found it under: `/etc/ipython/ipython_kernel_config.py`.

**Comment by santoshSAB** [comment]
HI , I have the same problem. Can you help me where and how I fix this ? I wanted to avoid this error coming up on the logs ?

**Comment by jnissin** [comment]
For me the solution was to cleanup the unnecessary extensions in `/etc/ipython/ipython_kernel_config.py`, namely the `beatrix_jupyterlab` extension.
