### ISSUE TITLE
IPyKernel throws cannot import name write_connection_file

### ISSUE THREAD

**Issue by tungalbert99** [ipython/ipykernel#967]
On Python 3.9.13 with the following versions, IPyKernel fails "python -m ipykernel install --user --name=myenv" 

```
jupyter               1.0.0
jupyter-client        7.3.4
jupyter-console       6.4.4
jupyter-core          4.11.1
jupyterlab-pygments   0.2.2
jupyterlab-widgets    1.1.1
```

Stack Trace:
```
[REMOVED]lib/python3.9/site-packages/jupyter_client/__init__.py:23: UserWarning: Could not import submodules
  warnings.warn("Could not import submodules")
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "[REMOVED]lib/python3.9/site-packages/ipykernel/__init__.py", line 5, in <module>
    from .connect import *  # noqa
  File "[REMOVED]/lib/python3.9/site-packages/ipykernel/connect.py", line 12, in <module>
    from jupyter_client import write_connection_file
ImportError: cannot import name 'write_connection_file' from 'jupyter_client' ([REMOVED]/lib/python3.9/site-packages/jupyter_client/__init__.py)
```

**Comment by blink1073** [comment]
Hi @tungalbert99, I'm not sure why it is hitting the `warnings.warn("Could not import submodules")` condition [here](https://github.com/jupyter/jupyter_client/blob/b2fcb529efc86268fc5e9ead0524bcd2e9585b0c/jupyter_client/__init__.py#L23) in your setup.  Can you please try editing `lib/python3.9/site-packages/jupyter_client/__init__.py` to call `raise` after the warning and give the traceback?

**Comment by blink1073** [comment]
Thanks for the additional context @kendallroth!

**Comment by tungalbert99** [comment]
@Sofiia2001 I'm not entirely sure. I ended up re-creating a new environment and it started working again.

**Comment by spookyuser** [comment]
This happened to me on linux what I had to do was actually install libffi and then uninstall, reinstall pyenv installations from this stackoverflow answer https://stackoverflow.com/a/60374453/1649917

```bash
sudo apt-get install libffi-dev
pyenv uninstall 3.7.6
pyenv install 3.7.6
```
